require('dotenv').config();
const express=require('express'),cors=require('cors'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),Database=require('better-sqlite3');
const app=express(); app.use(cors()); app.use(express.json());
const PORT=process.env.PORT||3000, SECRET=process.env.JWT_SECRET||'CHANGE_THIS_SECRET';
const db=new Database('mercados.db');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,usd REAL DEFAULT 10000,ars REAL DEFAULT 10000000,btc REAL DEFAULT 0,eth REAL DEFAULT 0,sol REAL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,type TEXT NOT NULL,asset TEXT NOT NULL,quantity REAL NOT NULL,price REAL NOT NULL,total REAL NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));`);
const token=id=>jwt.sign({userId:id},SECRET,{expiresIn:'7d'});
function auth(req,res,next){const h=req.headers.authorization;if(!h?.startsWith('Bearer '))return res.status(401).json({error:'Token requerido'});try{req.userId=jwt.verify(h.slice(7),SECRET).userId;next()}catch{return res.status(401).json({error:'Token inválido'})}}
app.get('/',(q,s)=>s.json({ok:true,service:'Mercados Globales API',mode:'DEMO'}));
app.post('/api/register',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!email||!password)return res.status(400).json({error:'Email y contraseña son obligatorios'});if(password.length<8)return res.status(400).json({error:'La contraseña debe tener al menos 8 caracteres'});if(db.prepare('SELECT id FROM users WHERE email=?').get(email))return res.status(409).json({error:'El usuario ya existe'});const hash=await bcrypt.hash(password,12),r=db.prepare('INSERT INTO users(email,password) VALUES(?,?)').run(email,hash);res.status(201).json({message:'Usuario creado',token:token(r.lastInsertRowid)})}catch(e){console.error(e);res.status(500).json({error:'Error interno'})}});
app.post('/api/login',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),u=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!u||!(await bcrypt.compare(password,u.password)))return res.status(401).json({error:'Credenciales incorrectas'});res.json({message:'Login correcto',token:token(u.id)})}catch{res.status(500).json({error:'Error interno'})}});
app.get('/api/me',auth,(req,res)=>{const u=db.prepare('SELECT id,email,usd,ars,btc,eth,sol,created_at FROM users WHERE id=?').get(req.userId);if(!u)return res.status(404).json({error:'Usuario no encontrado'});res.json(u)});
app.post('/api/trade',auth,(req,res)=>{try{const {type,asset}=req.body,q=Number(req.body.quantity),p=Number(req.body.price);if(!['buy','sell'].includes(type))throw Error('Tipo de operación inválido');if(!['btc','eth','sol'].includes(asset))throw Error('Activo inválido');if(!Number.isFinite(q)||!Number.isFinite(p)||q<=0||p<=0)throw Error('Cantidad o precio inválido');const total=q*p,u=db.prepare('SELECT * FROM users WHERE id=?').get(req.userId);if(!u)throw Error('Usuario no encontrado');const tx=db.transaction(()=>{if(type==='buy'){if(u.usd<total)throw Error('Saldo USD insuficiente');db.prepare(`UPDATE users SET usd=usd-?,${asset}=${asset}+? WHERE id=?`).run(total,q,req.userId)}else{if(u[asset]<q)throw Error(`Saldo ${asset.toUpperCase()} insuficiente`);db.prepare(`UPDATE users SET usd=usd+?,${asset}=${asset}-? WHERE id=?`).run(total,q,req.userId)}db.prepare('INSERT INTO transactions(user_id,type,asset,quantity,price,total) VALUES(?,?,?,?,?,?)').run(req.userId,type,asset,q,p,total)});tx();res.json({success:true,type,asset,quantity:q,price:p,total})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/transactions',auth,(req,res)=>res.json(db.prepare('SELECT id,type,asset,quantity,price,total,created_at FROM transactions WHERE user_id=? ORDER BY id DESC').all(req.userId)));
app.listen(PORT,'0.0.0.0',()=>console.log(`API escuchando en puerto ${PORT}`));
